import { createApp } from "vue";
import App from "./App.vue";
import router from "./router.js";
import store from "./store/index.js";
import BaseCard from "./components/ui/BaseCard.vue";
import BaseButton from "./components/ui/BaseButton.vue";
import FancyButton from "./components/ui/FancyButton.vue";
import Button from "./components/ui/neumorphicUI/button/Button.vue";
import Card from "./components/ui/neumorphicUI/card/Card.vue";
import IconButton from "./components/ui/neumorphicUI/icon-button/IconButton.vue";
import Checkbox from "./components/ui/neumorphicUI/checkbox/Checkbox.vue";
import ToggleButton from "./components/ui/neumorphicUI/toggle-button/ToggleButton.vue";
import DecoratedIcon from "./components/ui/neumorphicUI/decorated-icon/DecoratedIcon.vue";

const app = createApp(App);
app.use(router);
app.use(store);
app.component("BaseCard", BaseCard);
app.component("BaseButton", BaseButton);
app.component("FancyButton", FancyButton);
app.component("Button", Button);
app.component("Card", Card);
app.component("IconButton", IconButton);
app.component("Checkbox", Checkbox);
app.component("ToggleButton", ToggleButton);
app.component("DecoratedIcon", DecoratedIcon);
app.mount("#app");
